#References

*   https://www.coursera.org/learn/linear-algebra-machine-learning
*   https://github.com/bundickm/CheatSheets 
*   https://en.wikipedia.org/wiki/Matrix_(mathematics)
*   https://en.wikipedia.org/wiki/Transformation_matrix
*   https://en.wikipedia.org/wiki/Gaussian_elimination
*   https://towardsdatascience.com/manually-computing-coefficients-for-an-ols-regression-using-python-50d8e413de
*   https://rpubs.com/aaronsc32/qr-decomposition-gram-schmidt
*   https://web.physics.utah.edu/~detar/lessons/python/numpy_eigen/node1.html
*   https://intuitive-math.club/linear-algebra/eigenbasis/
*   https://programmathically.com/eigenvalue-decomposition/#:~:text=The%20eigenvalue%20decomposition%20or%20eigendecomposition,every%20column%20is%20an%20eigenvector).
*   https://scipy.github.io/devdocs/tutorial/linalg.html
*   https://cmdlinetips.com/2020/03/linear-regression-using-matrix-multiplication-in-python-using-numpy/
*   https://machinelearningmastery.com/examples-of-linear-algebra-in-machine-learning/
*   Curso Herramientas Matemáticas y Computacionales para IA. JL Paniagua


#Matrices

A rectangular grid of numbers arranged in rows and columns. Variables that represent matrices are typically written as capital letters (boldfaced as well if you want to be super formal).

\begin{align}
A = 
    \begin{bmatrix}
           1 & 2 & 3\\
           4 & 5 & 6\\
           7 & 8 & 9
    \end{bmatrix}
    \qquad
    B = \begin{bmatrix}
           1 & 2 & 3\\
           4 & 5 & 6
    \end{bmatrix}
 \end{align}



In [ ]:
A = np.array([[1, 2, 3], 
              [4, 5, 6],
              [7, 8, 9]])
B = np.array([[1, 2, 3], 
              [4, 5, 6]])

print(A.shape,B.shape)


#Matrix operations






##Matrix addition

If A and B are matrices of the same size, then they can be added.

\begin{align}
A = 
    \begin{bmatrix}
           1 & 2 & 3\\
           4 & 5 & 6\\
           7 & 8 & 9
    \end{bmatrix}
    \qquad
    B = \begin{bmatrix}
           1 & 2 & 3\\
           4 & 5 & 6
    \end{bmatrix}
        \qquad
    C = \begin{bmatrix}
           4 & 7 & 8\\
           3 & 7 & 9 \\
           3 & 4 & 8 \\
    \end{bmatrix}
 \end{align}

\begin{align}
A+B \text{ is not possible}\\
A+C \text{ is possible}
\end{align}

The sum $A+B$ of two $m$-by-$n$ matrices $A$ and $B$ is calculated entrywise:
$(A + B)_{i,j} = A_{i,j} + B_{i,j}$, where $1 ≤ i ≤ m$ and $1 ≤ j ≤ n$.





In [ ]:
A = np.array([[1, 2, 3], 
              [4, 5, 6],
              [7, 8, 9]])
C = np.array([[4, 7, 8], 
              [3, 7, 9],
              [3, 4, 8]])
B = np.array([[1, 2, 3], 
              [4, 5, 6]])
print(A+C)
#print(A+B)

##Scalar multiplication

The product $cA$ of a scalar c and a matrix A is computed by multiplying every entry of A by c:
$(cA)_{i,j} = c · A_{i,j}$.
This is not the same as "scalar product".

In [ ]:
print(A)
print(2*A)

##Transposition
The transpose of an $m$-by-$n$ matrix $A$ is the $n$-by-$m$ matrix $A^T$ formed by turning rows into columns and vice versa:
$A^T_{i,j} = A_{j,i}$.

In [ ]:
print(B)
print(B.transpose())

##Matrix multiplication
Multiplication of two matrices is defined if and only if the number of columns of the left matrix is the same as the number of rows of the right matrix. If A is an m-by-n matrix and B is an n-by-p matrix, then their matrix product AB is the m-by-p matrix whose entries are given by dot product of the corresponding row of A and the corresponding column of B.

\begin{align}
{\displaystyle [\mathbf {AB} ]_{i,j}=a_{i,1}b_{1,j}+a_{i,2}b_{2,j}+\cdots +a_{i,n}b_{n,j}=\sum _{r=1}^{n}a_{i,r}b_{r,j},}
\end{align}

In [ ]:

import urllib.request
from IPython.display import Image, display
urllib.request.urlretrieve(
  'https://upload.wikimedia.org/wikipedia/commons/e/e5/MatrixMultiplication.png','MatrixMultiplication.png')
display(Image("MatrixMultiplication.png", width=400, height=250))


Matrix multiplication satisfies the rules (AB)C = A(BC) (associativity), and (A + B)C = AC + BC as well as C(A + B) = CA + CB (left and right distributivity), whenever the size of the matrices is such that the various products are defined. The product AB may be defined without BA being defined, namely if A and B are m-by-n and n-by-k matrices, respectively, and m ≠ k. Even if both products are defined, they generally need not be equal, that is: AB ≠ BA,
In other words, matrix multiplication is not commutative,

In [ ]:
print(A.dot(C))
print(C.dot(A))

#Matrix transformations

Matrices and matrix multiplication are the basis for linear transformations, also known as linear maps. A real m-by-n matrix A gives rise to a linear transformation $R^n → R^m$ mapping each vector x in $R^n$ to the (matrix) product Ax, which is a vector in $R^m$. Conversely, each linear transformation f: Rn → Rm arises from a unique m-by-n matrix A: explicitly, the (i, j)-entry of A is the ith coordinate of f(ej), where ej = (0,...,0,1,0,...,0) is the unit vector with 1 in the jth position and 0 elsewhere. The matrix A is said to represent the linear map f, and A is called the transformation matrix of f.

For example, the 2×2 matrix

$A=\begin{bmatrix}a&c\\b&d\end{bmatrix}$

can be viewed as the transform of the unit square into a parallelogram with vertices at (0, 0), (a, b), (a + c, b + d), and (c, d). 

The parallelogram pictured at the right is obtained by multiplying A with each of the column vectors 
[0,0],[1,0],[1,1] and [0,1] in turn. These vectors define the vertices of the unit square.


In [ ]:
#plot the unit square
def plot_un_sq(e0,e1,e2,e1n,e2n,mycolor):
  e3=e1+e2
  un_sq=np.array([e0,e1,e2,e3])
  vectors_rn = np.array([[*e0, *e1],
                      [*e0, *e2]])
  X0, Y0, Xf, Yf = zip(*vectors_rn)
  ax = plt.gca()
  x_lim=[un_sq.min(axis=0)[0]-1, un_sq.max(axis=0)[0]+1]
  y_lim=[un_sq.min(axis=0)[1]-1, un_sq.max(axis=0)[1]+1]
#  print(x_lim); print(y_lim)
  
  ax.quiver(X0, Y0, Xf, Yf, angles='xy', scale_units='xy',
          color=[mycolor,mycolor],scale=1)
  #ax.annotate(e1n + f'({e1[0]},{e1[1]})', (e1[0],e1[1]),fontsize=14)
  #ax.annotate(e2n + f'({e2[0]},{e2[1]})', (e2[0],e2[1]),fontsize=14)
  bx1=[e0[0],e1[0],e3[0]]
  bx2=[e0[0],e2[0],e3[0]]
  by1=[e0[1],e1[1],e3[1]]
  by2=[e0[1],e2[1],e3[1]]
  plt.fill(
    np.append(bx1, bx2[::-1]),
    np.append(by1, by2[::-1]), 
    mycolor, alpha=0.2)
  ax.set_xlim(x_lim);ax.set_ylim(y_lim)

plt.figure(); 
e0=[0,0]; e1=np.array([1,0]); e2=np.array([0,1])
print(e1,e2)
e3=e1+e2
e1n='e1'; e2n='e2'
mycolor='b'
plot_un_sq(e0,e1,e2,e1n,e2n,mycolor)


In [ ]:
#plot a Horizontal Shear
plt.figure(); 
e0=[0,0]; e1=np.array([1,0]); e2=np.array([0,1])
e3=e1+e2
e1n='e1'; e2n='e2'
mycolor='b'
plot_un_sq(e0,e1,e2,e1n,e2n,mycolor)



b0=e0
tm=np.array([[1,1.25],
            [0,1]])
b1=tm.dot(e1)      
b2=tm.dot(e2)
b3=b1+b2
b1n='b1'; b2n='b2'
mycolor='r'
plot_un_sq(b0,b1,b2,b1n,b2n,mycolor)
print(e1,e2)
print(b1,b2)


In [ ]:
#plot a reflection
plt.figure(); 
e0=[0,0]; e1=np.array([1,0]); e2=np.array([0,1])
e3=e1+e2
e1n='e1'; e2n='e2'
mycolor='b'
plot_un_sq(e0,e1,e2,e1n,e2n,mycolor)


b0=e0
tm=np.array([[-1,0],
            [0,1]])
b1=tm.dot(e1)      
b2=tm.dot(e2)
b3=b1+b2
b1n='b1'; b2n='b2'
mycolor='r'
plot_un_sq(b0,b1,b2,b1n,b2n,mycolor)
print(e1,e2)
print(b1,b2)



In [ ]:
#plot a squeeze
plt.figure(); 
e0=[0,0]; e1=np.array([1,0]); e2=np.array([0,1])
e3=e1+e2
e1n='e1'; e2n='e2'
mycolor='b'
plot_un_sq(e0,e1,e2,e1n,e2n,mycolor)


b0=e0
tm=np.array([[3/2,0],
            [0,2/3]])
b1=tm.dot(e1)      
b2=tm.dot(e2)
b3=b1+b2
b1n='b1'; b2n='b2'
mycolor='r'
plot_un_sq(b0,b1,b2,b1n,b2n,mycolor)
print(e1,e2)
print(b1,b2)


In [ ]:
#plot a scaling
plt.figure(); 
e0=[0,0]; e1=np.array([1,0]); e2=np.array([0,1])
e3=e1+e2
e1n='e1'; e2n='e2'
mycolor='b'
plot_un_sq(e0,e1,e2,e1n,e2n,mycolor)


b0=e0
tm=np.array([[3/2,0],
            [0,3/2]])
b1=tm.dot(e1)      
b2=tm.dot(e2)
b3=b1+b2
b1n='b1'; b2n='b2'
mycolor='r'
plot_un_sq(b0,b1,b2,b1n,b2n,mycolor)
print(e1,e2)
print(b1,b2)


In [ ]:
#plot a rotation
plt.figure(); 
e0=[0,0]; e1=np.array([1,0]); e2=np.array([0,1])
e3=e1+e2
e1n='e1'; e2n='e2'
mycolor='b'
plot_un_sq(e0,e1,e2,e1n,e2n,mycolor)


b0=e0
tm=np.array([[np.cos(np.pi/6),-np.sin(np.pi/6)],
            [np.sin(np.pi/6),np.cos(np.pi/6)]])
b1=tm.dot(e1)      
b2=tm.dot(e2)
b3=b1+b2
b1n='b1'; b2n='b2'
mycolor='r'
plot_un_sq(b0,b1,b2,b1n,b2n,mycolor)
print(e1,e2)
print(b1,b2)


#Combination of matrix transformations
The order of the matrix transformations is not conmutative. That is:
$A_2(A_1r)$ is not the same as $A_1(A_2r)$ 

In [ ]:
#A2(A1r)
plt.figure(); 
e0=[0,0]; e1=np.array([1,0]); e2=np.array([0,1])
e3=e1+e2
e1n='e1'; e2n='e2'
mycolor='b'
plot_un_sq(e0,e1,e2,e1n,e2n,mycolor)


b0=e0
tm1=np.array([[0,1],
            [-1,0]])
b1=tm1.dot(e1)      
b2=tm1.dot(e2)
b3=b1+b2
b1n='b1'; b2n='b2'
mycolor='r'
plot_un_sq(b0,b1,b2,b1n,b2n,mycolor)

c0=b0
tm2=np.array([[-1,0],
            [0,1]])
c1=tm2.dot(b1)      
c2=tm2.dot(b2)
c3=c1+c2
c1n='c1'; c2n='c2'
mycolor='y'
plot_un_sq(c0,c1,c2,c1n,c2n,mycolor)

print(e1,e2)
print(b1,b2)
print(c1,c2)


In [ ]:
#A1(A2r)
plt.figure(); 
e0=[0,0]; e1=np.array([1,0]); e2=np.array([0,1])
e3=e1+e2
e1n='e1'; e2n='e2'
mycolor='b'
plot_un_sq(e0,e1,e2,e1n,e2n,mycolor)


b0=e0
tm1=np.array([[-1,0],
            [0,1]])
b1=tm1.dot(e1)      
b2=tm1.dot(e2)
b3=b1+b2
b1n='b1'; b2n='b2'
mycolor='r'
plot_un_sq(b0,b1,b2,b1n,b2n,mycolor)

c0=b0
tm2=np.array([[0,1],
            [-1,0]])
c1=tm2.dot(b1)      
c2=tm2.dot(b2)
c3=c1+c2
c1n='c1'; c2n='c2'
mycolor='y'
plot_un_sq(c0,c1,c2,c1n,c2n,mycolor)

print(e1,e2)
print(b1,b2)
print(c1,c2)


### Square Matrices:

A square matrix is any matrix that has the same number of rows as columns:

\begin{align}
A =
\begin{bmatrix}
  a_{1,1}
\end{bmatrix}
\qquad
B =
\begin{bmatrix}
b_{1,1} & b_{1,2} \\
b_{2,1} & b_{2,2}
\end{bmatrix}
\qquad
C =
\begin{bmatrix}
c_{1,1} & c_{1,2} & c_{1,3} \\
c_{2,1} & c_{2,2} & c_{2,3} \\
c_{3,1} & c_{3,2} & c_{3,3} 
\end{bmatrix}
\end{align}

### Special Kinds of Square Matrices

**Diagonal:** Values on the main diagonal, zeroes everywhere else.

\begin{align}
A =
\begin{bmatrix}
a_{1,1} & 0 & 0 \\
0 & a_{2,2} & 0 \\
0 & 0 & a_{3,3} 
\end{bmatrix}
\end{align}

**Upper Triangular:** Values on and above the main diagonal, zeroes everywhere else.

\begin{align}
B =
\begin{bmatrix}
b_{1,1} & b_{1,2} & b_{1,3} \\
0 & b_{2,2} & b_{2,3} \\
0 & 0 & b_{3,3} 
\end{bmatrix}
\end{align}

**Lower Triangular:** Values on and below the main diagonal, zeroes everywhere else.

\begin{align}
C =
\begin{bmatrix}
c_{1,1} & 0 & 0 \\
c_{2,1} & c_{2,2} & 0 \\
c_{3,1} & c_{3,2} & c_{3,3} 
\end{bmatrix}
\end{align}

**Identity Matrix:** A diagonal matrix with ones on the main diagonal and zeroes everywhere else. The product of the any square matrix and the identity matrix is the original square matrix $AI == A$. Also, any matrix multiplied by its inverse will give the identity matrix as its product.  $AA^{-1} = I$

\begin{align}
D =
\begin{bmatrix}
  1
\end{bmatrix}
\qquad
E =
\begin{bmatrix}
1 & 0 \\
0 & 1
\end{bmatrix}
\qquad
F =
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 
\end{bmatrix}
\end{align}

**Symmetric:** The numbers above the main diagonal are mirrored below/across the main diagonal.

\begin{align}
G =
\begin{bmatrix}
1 & 4 & 5 \\
4 & 2 & 6 \\
5 & 6 & 3 
\end{bmatrix}
\end{align}




#Some more functions...


In [ ]:
d = np.eye(2)        # Create a 2x2 identity matrix
e = np.random.random((2,2)) # Create an array filled with random values
print(d @ e)
print(d.dot(e))

x = np.array([ 3, -4,  0])
print(np.diag(x))

U=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(U)
print("Triangular inferior:\n",np.tril(U))
print("Triangular superior:\n",np.triu(U))


[[0.29089217 0.30794486]
 [0.0911762  0.47841709]]
[[0.29089217 0.30794486]
 [0.0911762  0.47841709]]
[[ 3  0  0]
 [ 0 -4  0]
 [ 0  0  0]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Triangular inferior:
 [[1 0 0]
 [4 5 0]
 [7 8 9]]
Triangular superior:
 [[1 2 3]
 [0 5 6]
 [0 0 9]]
