In [1]:
import numpy as np

**Procesamiento de un Neurona Artificial**

Crear el vector de entrada X

In [2]:
X=np.array([[1],[0.5],[-0.6]])
print(X)

[[ 1. ]
 [ 0.5]
 [-0.6]]


Crear vector de pesos W

In [3]:
W=np.array([[1.0],[-0.7],[-1.0]])
print(W)

[[ 1. ]
 [-0.7]
 [-1. ]]


Calculo de la neta

In [4]:
Neta=(np.sum(np.multiply(X,W)))
print(Neta)

1.25


Function de activacion sigmoidal

In [5]:
Y=1.0/(1+np.exp(-Neta))
print(Y)

0.7772998611746911


**Procesamiento de una capa de Neuronas**

W y B matricial, Wp(4x3), B(3x1) y X(4x1)

In [6]:
Wp=np.array([[1.5,0.5, -0.5],[0.7,-0.8, 1.5],[-1.0,1.2, 0.3],[1.0,0.2,-0.3]])
print(Wp)
B=np.array([[0.7],[-0.3],[-0.5]])
print(B)
X=np.array([[1],[0.5],[-0.5],[1]])
print(X)

[[ 1.5  0.5 -0.5]
 [ 0.7 -0.8  1.5]
 [-1.   1.2  0.3]
 [ 1.   0.2 -0.3]]
[[ 0.7]
 [-0.3]
 [-0.5]]
[[ 1. ]
 [ 0.5]
 [-0.5]
 [ 1. ]]


Neta matricial

In [7]:
Neta=((np.matmul(np.transpose(Wp),X))+B)
print(Neta)

[[ 4.05]
 [-0.6 ]
 [-0.7 ]]


Salida Matricial

In [8]:
Y=1.0/(1+np.exp(-Neta))
print(Y)

[[0.98287597]
 [0.35434369]
 [0.33181223]]


In [27]:
Wp1=np.array([[1.5,0.5, -0.5,-0.5,-0.5],[0.7,-0.8, 1.5,1.5,1.5],[-1.0,1.2, 0.3,0.3,0.3]])
print(Wp1)
B1=np.array([[0.7],[-0.3],[0.5],[-0.2],[0.1]])
print(B1)

[[ 1.5  0.5 -0.5 -0.5 -0.5]
 [ 0.7 -0.8  1.5  1.5  1.5]
 [-1.   1.2  0.3  0.3  0.3]]
[[ 0.7]
 [-0.3]
 [ 0.5]
 [-0.2]
 [ 0.1]]


In [22]:
Neta1=((np.matmul((Wp1.T),Y))+B1)
print(Neta1)

[[ 2.09054231]
 [ 0.3061377 ]
 [ 0.63962123]
 [-0.06037877]
 [ 0.23962123]]


In [23]:
Y2=1.0/(1+np.exp(-Neta1))
print(Y2)

[[0.88998054]
 [0.57594224]
 [0.65466783]
 [0.48490989]
 [0.5596203 ]]
